Reflection
Constantijn-Dinklo/3D_Noise_Modelling pull request #14
Opened 2020-05-18 12:23 UTC by denisgiannelli

Reflection paths.

2020-05-18 13:55 UTC, Constantijn-Dinklo requested changes

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +        p2 [x(float),y(float)]
This should be in the format:
var_name : type - explination
so for you p1 : [x(float), y(float)] - The starting point in the line. 
Use a different explination if I'm wrong.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +        parameters [a_norm(float),b_norm(float),c_norm(float)]
This should be in the format:
var_name : type
Just add a :

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +        return [p_mirror_x,p_mirror_y]
Has the same explination as the function before (get_mirror_point) and almost does the same thing. Is the functionality incorrect or the explination?

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +    def split_lineseg2(self,dim,lineseg):
Re-name to 'splint_lineseg_dim' or something similar, but not 2.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +                        p1_list.append([s,ref_z,r])
p1_list is never used.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +        for candidate in c_list:
What is c_list? It has not been defined yet.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +                                        p2_list.append([s,b_z,candidate[1],r_closest])
p2_list is never used.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
>      r_dict = { }
Define these in the __init__ function.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +    read_points('//Users/denisgiannelli/Documents/DOCS_TU_DELFT/_4Q/GEO1101/06_DATA/03_midpresentation/receivers.gpkg',r_dict)
Since you define the dictionaries in the __init__ fuction, you don't need to pass them into the functions here.

2020-05-18 13:55 UTC, Constantijn-Dinklo commented on code/simpleReflection.py
> +    p2_list = [ ]
If these are here just for outputting/testing purposes, then they are fine to stay here. And you can discard my earlier comments for them.

If they are actually used in the calculations/computations then they need to be moved into the __init__ function.

2020-05-18 14:18 UTC, denisgiannelli commented on code/simpleReflection.py
> +        p2 [x(float),y(float)]
Ok!

2020-05-18 14:18 UTC, denisgiannelli commented on code/simpleReflection.py
> +        parameters [a_norm(float),b_norm(float),c_norm(float)]
Ok!

2020-05-18 14:23 UTC, denisgiannelli commented on code/simpleReflection.py
> +        return [p_mirror_x,p_mirror_y]
The explanation was incorrect. My bad!

2020-05-18 14:26 UTC, denisgiannelli commented on code/simpleReflection.py
> +    def split_lineseg2(self,dim,lineseg):
Ok!

2020-05-18 14:33 UTC, denisgiannelli commented on code/simpleReflection.py
> +                        p1_list.append([s,ref_z,r])
p1_list  is used for writing the CSV file, and not for the purpose of the code itself. So I understand that this should not be moved to the __init__ function, right?

2020-05-18 14:33 UTC, denisgiannelli commented on code/simpleReflection.py
> +        for candidate in c_list:
c_list is the candidate points list. This one should be moved to __init__ indeed.

2020-05-18 14:35 UTC, denisgiannelli commented on code/simpleReflection.py
> +                                        p2_list.append([s,b_z,candidate[1],r_closest])
like p1_list, p2_list is used for writing the CSV file, and not for the purpose of the code itself. So I understand that this should not be moved to the init function, right?

2020-05-18 14:36 UTC, denisgiannelli commented on code/simpleReflection.py
>      r_dict = { }
Aren't they already defined?

2020-05-18 14:42 UTC, denisgiannelli commented on code/simpleReflection.py
> +    p2_list = [ ]
I put c_list in __init__ , but the other two (p1_list) and (p2_list) are only used for outputting indeed.

2020-05-18 14:42 UTC, denisgiannelli commented on code/simpleReflection.py
> +    read_points('//Users/denisgiannelli/Documents/DOCS_TU_DELFT/_4Q/GEO1101/06_DATA/03_midpresentation/receivers.gpkg',r_dict)
I don't understand this. Maybe you could show me how to do it later on? :)

2020-05-19 14:17 UTC, Constantijn-Dinklo approved these changes

2020-05-19 14:17 UTC, merged